Repository red-hat-storage/odf-must-gather, pull requests merged in 2023-07, with the labels that each got.

#36 Collect network-attachment-definitions for multus feature
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#35 Bug 2215917: collect the status for RBD-images
  must-gather/collection-scripts/gather_ceph_resources
Labels: bugzilla/severity-urgent, bugzilla/valid-bug

#31 must-gather: Add DCO file
  CONTRIBUTING.md
  DCO
Labels: approved, lgtm, ok-to-test

#30 collect logs for managedfusionoffering CR
  must-gather/collection-scripts/gather_namespaced_resources
Labels: approved

#27 Adding namespacestore in noobaa collection_script
  must-gather/collection-scripts/gather_noobaa_resources
Labels: approved

#32 Gather: Use utility function to append to debug logs
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_ceph_resources
  must-gather/collection-scripts/gather_clusterscoped_resources
  must-gather/collection-scripts/gather_common_ceph_resources
  must-gather/collection-scripts/gather_namespaced_resources
  must-gather/collection-scripts/gather_noobaa_resources
  must-gather/collection-scripts/pre-install.sh
  must-gather/collection-scripts/utils.sh
Labels: ok-to-test
