Repository red-hat-storage/odf-must-gather, pull requests merged in 2024-08, with the labels that each got.

#186 Update ImagePullPolicy to Always
  templates/pod.template
Labels: approved, lgtm

#185 Include pod metadata in must-gather output
  collection-scripts/gather
  collection-scripts/utils.sh
Labels: approved, lgtm

#188 add new crds created by ceph csi operation
  collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#190 Bug 2308101: logrotate: add logrotate functionality for csi operator
  collection-scripts/gather_ceph_logs
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#191 Bug 2308101: logrotate: add logrotate functionality for csi operator
  collection-scripts/gather_ceph_logs
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high, do-not-merge/hold

#193 Bug 2308101: logrotate: add logrotate functionality for csi operator
  collection-scripts/gather_ceph_logs
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#194 Add missing PIDs while collecting ceph logs
  collection-scripts/gather_ceph_logs
Labels: approved, lgtm
