Repository red-hat-storage/odf-must-gather, pull requests merged in 2024-11, with the labels that each got.

#205 include storageclusterpeer info
  collection-scripts/gather_clusterscoped_resources
Labels: approved, lgtm

#209 Syncing latest changes from main for odf-must-gather
  Dockerfile
  collection-scripts/gather_clusterscoped_resources
Labels: approved, lgtm

#206 Add new flag to collect minimal resources
  collection-scripts/gather
  collection-scripts/gather_minimal_resources
Labels: approved, lgtm, ok-to-test

#210 Syncing latest changes from main for odf-must-gather
  collection-scripts/gather
  collection-scripts/gather_minimal_resources
Labels: approved, lgtm

#211 Fix collection time
  collection-scripts/gather
Labels: approved, lgtm

#212 Syncing latest changes from main for odf-must-gather
  collection-scripts/gather
Labels: approved, lgtm

#213 DFBUGS-727: gather: Add a script to collect external cluster details
  collection-scripts/gather_namespaced_resources
Labels: approved, lgtm

#214 Syncing latest changes from main for odf-must-gather
  collection-scripts/gather_namespaced_resources
Labels: approved, lgtm, jira/valid-bug
